/**
 * 微信公众号与中国广告法内容合规词库与规则定义
 * 包含绝对化极限词、过度夸大承诺、诱导导流敏感词以及合规替换建议
 */

export interface ComplianceRule {
  id: string;
  pattern: RegExp;
  word: string;
  category: "extreme" | "promise" | "inducement";
  categoryName: string;
  severity: "warning" | "danger";
  suggestion: string;
  description: string;
}

export const COMPLIANCE_RULES: ComplianceRule[] = [
  // 1. 绝对化与极限用语（广告法第 9 条明令禁止）
  {
    id: "ext-top-tier",
    pattern: /顶级/g,
    word: "顶级",
    category: "extreme",
    categoryName: "广告法极限词",
    severity: "danger",
    suggestion: "高品质 / 卓越",
    description: "广告法禁止使用绝对化用语描述产品或技术能力",
  },
  {
    id: "ext-highest",
    pattern: /最高级/g,
    word: "最高级",
    category: "extreme",
    categoryName: "广告法极限词",
    severity: "danger",
    suggestion: "高水准 / 进阶",
    description: "最高级等绝对化表述容易触发平台合规审核处罚",
  },
  {
    id: "ext-best",
    pattern: /最佳/g,
    word: "最佳",
    category: "extreme",
    categoryName: "广告法极限词",
    severity: "danger",
    suggestion: "优秀 / 良好 / 适宜",
    description: "避免在无权威资质前提下使用'最佳'等排他性修饰",
  },
  {
    id: "ext-no1-brand",
    pattern: /第一品牌/g,
    word: "第一品牌",
    category: "extreme",
    categoryName: "广告法极限词",
    severity: "danger",
    suggestion: "头部品牌 / 知名品牌",
    description: "禁止在宣传中使用未经官方认证的'第一品牌'等说法",
  },
  {
    id: "ext-universal",
    pattern: /万能/g,
    word: "万能",
    category: "extreme",
    categoryName: "广告法极限词",
    severity: "warning",
    suggestion: "功能全面 / 适用广泛",
    description: "工具或产品宣称'万能'属于过度夸大",
  },
  {
    id: "ext-extreme-quality",
    pattern: /极品/g,
    word: "极品",
    category: "extreme",
    categoryName: "广告法极限词",
    severity: "warning",
    suggestion: "精品 / 优质品",
    description: "极品属于不可量化的绝对化夸张修饰",
  },
  {
    id: "ext-most-advanced",
    pattern: /最先进/g,
    word: "最先进",
    category: "extreme",
    categoryName: "广告法极限词",
    severity: "danger",
    suggestion: "前沿 / 领先 / 先进",
    description: "未经第三方公证的技术禁止直接自称'最先进'",
  },
  {
    id: "ext-first-in-nation",
    pattern: /全国首家/g,
    word: "全国首家",
    category: "extreme",
    categoryName: "广告法极限词",
    severity: "danger",
    suggestion: "业内先行者 / 早期探索者",
    description: "首家、首发等表述需具备法定公证或登记证明",
  },
  {
    id: "ext-exclusive-debut",
    pattern: /独家首发/g,
    word: "独家首发",
    category: "extreme",
    categoryName: "广告法极限词",
    severity: "warning",
    suggestion: "特别推出 / 率先呈现",
    description: "独家表述需防范无版权或授权依据",
  },
  {
    id: "ext-absolute",
    pattern: /绝对/g,
    word: "绝对",
    category: "extreme",
    categoryName: "广告法极限词",
    severity: "warning",
    suggestion: "高度 / 充分 / 明确",
    description: "日常论述中过满的'绝对'在商品推广时易构成断言违规",
  },
  {
    id: "ext-unmatched",
    pattern: /绝无仅有/g,
    word: "绝无仅有",
    category: "extreme",
    categoryName: "广告法极限词",
    severity: "warning",
    suggestion: "难得一见 / 颇具特色",
    description: "排他性极端词语在广告文案中属于高风险用语",
  },
  {
    id: "ext-history-most",
    pattern: /史上最/g,
    word: "史上最",
    category: "extreme",
    categoryName: "广告法极限词",
    severity: "danger",
    suggestion: "格外突出 / 显著 / 备受关注",
    description: "标题党式'史上最...'极易被公众号平台标记低质或限流",
  },

  // 2. 虚假承诺与过度夸大
  {
    id: "prm-100-percent",
    pattern: /100%有效/g,
    word: "100%有效",
    category: "promise",
    categoryName: "夸大承诺",
    severity: "danger",
    suggestion: "效果显著 / 明显改善",
    description: "禁止在营销文案中给出 100% 有效性绝对承诺",
  },
  {
    id: "prm-zero-risk",
    pattern: /零风险/g,
    word: "零风险",
    category: "promise",
    categoryName: "夸大承诺",
    severity: "danger",
    suggestion: "门槛友好 / 稳健可控",
    description: "财经、理财与教育类目禁止宣传'零风险'",
  },
  {
    id: "prm-guaranteed-pass",
    pattern: /包过/g,
    word: "包过",
    category: "promise",
    categoryName: "夸大承诺",
    severity: "danger",
    suggestion: "助力备考 / 系统提升",
    description: "培训与知识自媒体禁止使用保过/包过等承诺字眼",
  },
  {
    id: "prm-sure-profit",
    pattern: /稳赚不赔/g,
    word: "稳赚不赔",
    category: "promise",
    categoryName: "夸大承诺",
    severity: "danger",
    suggestion: "具备增值潜力",
    description: "任何涉及投资回报的内容均禁止承诺稳赚不赔",
  },
  {
    id: "prm-kill-all",
    pattern: /秒杀所有/g,
    word: "秒杀所有",
    category: "promise",
    categoryName: "夸大承诺",
    severity: "warning",
    suggestion: "表现优异 / 颇具竞争力",
    description: "贬损竞品的夸大式秒杀可能违反反不正当竞争法",
  },

  // 3. 诱导导流与平台限流雷区
  {
    id: "ind-reply-get",
    pattern: /回复领取/g,
    word: "回复领取",
    category: "inducement",
    categoryName: "诱导行为",
    severity: "warning",
    suggestion: "文末自取 / 查看详情获取",
    description: "易被微信识别为诱导私信或诱导互动",
  },
  {
    id: "ind-add-wechat",
    pattern: /加微获取/g,
    word: "加微获取",
    category: "inducement",
    categoryName: "诱导行为",
    severity: "warning",
    suggestion: "通过官方指引获取",
    description: "明文引导加私人微信易触发公众号防骚扰机制",
  },
  {
    id: "ind-join-group-free",
    pattern: /进群免费领/g,
    word: "进群免费领",
    category: "inducement",
    categoryName: "诱导行为",
    severity: "warning",
    suggestion: "参与交流学习",
    description: "诱导加群送资料是平台封禁和降权的高发行为",
  },
  {
    id: "ind-click-avatar",
    pattern: /点击头像/g,
    word: "点击头像",
    category: "inducement",
    categoryName: "诱导行为",
    severity: "warning",
    suggestion: "进入作者专栏",
    description: "诱导关注与跳转类固定套话建议润色为自然表述",
  },
];
